import React from "react"
import {Text,View,StatusBar,SafeAreaView,StyleSheet, TextInput, FlatList, Image, TouchableOpacity} from "react-native"
import {widthPercentageToDP as wp , heightPercentageToDP as hp} from "react-native-responsive-screen"
const UsersScreen = ({navigation}) => {
    const Data = [
        {
          "login": "tokuda109",
          "id": 108762,
          "node_id": "MDQ6VXNlcjEwODc2Mg==",
          "avatar_url": "https://avatars.githubusercontent.com/u/108762?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/tokuda109",
          "html_url": "https://github.com/tokuda109",
          "followers_url": "https://api.github.com/users/tokuda109/followers",
          "following_url": "https://api.github.com/users/tokuda109/following{/other_user}",
          "gists_url": "https://api.github.com/users/tokuda109/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/tokuda109/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/tokuda109/subscriptions",
          "organizations_url": "https://api.github.com/users/tokuda109/orgs",
          "repos_url": "https://api.github.com/users/tokuda109/repos",
          "events_url": "https://api.github.com/users/tokuda109/events{/privacy}",
          "received_events_url": "https://api.github.com/users/tokuda109/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "svallory",
          "id": 117560,
          "node_id": "MDQ6VXNlcjExNzU2MA==",
          "avatar_url": "https://avatars.githubusercontent.com/u/117560?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/svallory",
          "html_url": "https://github.com/svallory",
          "followers_url": "https://api.github.com/users/svallory/followers",
          "following_url": "https://api.github.com/users/svallory/following{/other_user}",
          "gists_url": "https://api.github.com/users/svallory/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/svallory/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/svallory/subscriptions",
          "organizations_url": "https://api.github.com/users/svallory/orgs",
          "repos_url": "https://api.github.com/users/svallory/repos",
          "events_url": "https://api.github.com/users/svallory/events{/privacy}",
          "received_events_url": "https://api.github.com/users/svallory/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "weldan",
          "id": 121695,
          "node_id": "MDQ6VXNlcjEyMTY5NQ==",
          "avatar_url": "https://avatars.githubusercontent.com/u/121695?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/weldan",
          "html_url": "https://github.com/weldan",
          "followers_url": "https://api.github.com/users/weldan/followers",
          "following_url": "https://api.github.com/users/weldan/following{/other_user}",
          "gists_url": "https://api.github.com/users/weldan/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/weldan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/weldan/subscriptions",
          "organizations_url": "https://api.github.com/users/weldan/orgs",
          "repos_url": "https://api.github.com/users/weldan/repos",
          "events_url": "https://api.github.com/users/weldan/events{/privacy}",
          "received_events_url": "https://api.github.com/users/weldan/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "gavinuhma",
          "id": 404716,
          "node_id": "MDQ6VXNlcjQwNDcxNg==",
          "avatar_url": "https://avatars.githubusercontent.com/u/404716?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/gavinuhma",
          "html_url": "https://github.com/gavinuhma",
          "followers_url": "https://api.github.com/users/gavinuhma/followers",
          "following_url": "https://api.github.com/users/gavinuhma/following{/other_user}",
          "gists_url": "https://api.github.com/users/gavinuhma/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/gavinuhma/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/gavinuhma/subscriptions",
          "organizations_url": "https://api.github.com/users/gavinuhma/orgs",
          "repos_url": "https://api.github.com/users/gavinuhma/repos",
          "events_url": "https://api.github.com/users/gavinuhma/events{/privacy}",
          "received_events_url": "https://api.github.com/users/gavinuhma/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "yijie",
          "id": 738268,
          "node_id": "MDQ6VXNlcjczODI2OA==",
          "avatar_url": "https://avatars.githubusercontent.com/u/738268?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/yijie",
          "html_url": "https://github.com/yijie",
          "followers_url": "https://api.github.com/users/yijie/followers",
          "following_url": "https://api.github.com/users/yijie/following{/other_user}",
          "gists_url": "https://api.github.com/users/yijie/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/yijie/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/yijie/subscriptions",
          "organizations_url": "https://api.github.com/users/yijie/orgs",
          "repos_url": "https://api.github.com/users/yijie/repos",
          "events_url": "https://api.github.com/users/yijie/events{/privacy}",
          "received_events_url": "https://api.github.com/users/yijie/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "filipediasf",
          "id": 1162685,
          "node_id": "MDQ6VXNlcjExNjI2ODU=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1162685?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/filipediasf",
          "html_url": "https://github.com/filipediasf",
          "followers_url": "https://api.github.com/users/filipediasf/followers",
          "following_url": "https://api.github.com/users/filipediasf/following{/other_user}",
          "gists_url": "https://api.github.com/users/filipediasf/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/filipediasf/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/filipediasf/subscriptions",
          "organizations_url": "https://api.github.com/users/filipediasf/orgs",
          "repos_url": "https://api.github.com/users/filipediasf/repos",
          "events_url": "https://api.github.com/users/filipediasf/events{/privacy}",
          "received_events_url": "https://api.github.com/users/filipediasf/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "savekirk",
          "id": 1415994,
          "node_id": "MDQ6VXNlcjE0MTU5OTQ=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1415994?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/savekirk",
          "html_url": "https://github.com/savekirk",
          "followers_url": "https://api.github.com/users/savekirk/followers",
          "following_url": "https://api.github.com/users/savekirk/following{/other_user}",
          "gists_url": "https://api.github.com/users/savekirk/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/savekirk/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/savekirk/subscriptions",
          "organizations_url": "https://api.github.com/users/savekirk/orgs",
          "repos_url": "https://api.github.com/users/savekirk/repos",
          "events_url": "https://api.github.com/users/savekirk/events{/privacy}",
          "received_events_url": "https://api.github.com/users/savekirk/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "zhuyinan",
          "id": 1510656,
          "node_id": "MDQ6VXNlcjE1MTA2NTY=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1510656?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/zhuyinan",
          "html_url": "https://github.com/zhuyinan",
          "followers_url": "https://api.github.com/users/zhuyinan/followers",
          "following_url": "https://api.github.com/users/zhuyinan/following{/other_user}",
          "gists_url": "https://api.github.com/users/zhuyinan/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/zhuyinan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/zhuyinan/subscriptions",
          "organizations_url": "https://api.github.com/users/zhuyinan/orgs",
          "repos_url": "https://api.github.com/users/zhuyinan/repos",
          "events_url": "https://api.github.com/users/zhuyinan/events{/privacy}",
          "received_events_url": "https://api.github.com/users/zhuyinan/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "constraint",
          "id": 1698071,
          "node_id": "MDQ6VXNlcjE2OTgwNzE=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1698071?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/constraint",
          "html_url": "https://github.com/constraint",
          "followers_url": "https://api.github.com/users/constraint/followers",
          "following_url": "https://api.github.com/users/constraint/following{/other_user}",
          "gists_url": "https://api.github.com/users/constraint/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/constraint/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/constraint/subscriptions",
          "organizations_url": "https://api.github.com/users/constraint/orgs",
          "repos_url": "https://api.github.com/users/constraint/repos",
          "events_url": "https://api.github.com/users/constraint/events{/privacy}",
          "received_events_url": "https://api.github.com/users/constraint/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "scrx",
          "id": 1715931,
          "node_id": "MDQ6VXNlcjE3MTU5MzE=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1715931?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/scrx",
          "html_url": "https://github.com/scrx",
          "followers_url": "https://api.github.com/users/scrx/followers",
          "following_url": "https://api.github.com/users/scrx/following{/other_user}",
          "gists_url": "https://api.github.com/users/scrx/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/scrx/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/scrx/subscriptions",
          "organizations_url": "https://api.github.com/users/scrx/orgs",
          "repos_url": "https://api.github.com/users/scrx/repos",
          "events_url": "https://api.github.com/users/scrx/events{/privacy}",
          "received_events_url": "https://api.github.com/users/scrx/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "ivychill",
          "id": 1735802,
          "node_id": "MDQ6VXNlcjE3MzU4MDI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1735802?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/ivychill",
          "html_url": "https://github.com/ivychill",
          "followers_url": "https://api.github.com/users/ivychill/followers",
          "following_url": "https://api.github.com/users/ivychill/following{/other_user}",
          "gists_url": "https://api.github.com/users/ivychill/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/ivychill/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/ivychill/subscriptions",
          "organizations_url": "https://api.github.com/users/ivychill/orgs",
          "repos_url": "https://api.github.com/users/ivychill/repos",
          "events_url": "https://api.github.com/users/ivychill/events{/privacy}",
          "received_events_url": "https://api.github.com/users/ivychill/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "luoyangylh",
          "id": 1758102,
          "node_id": "MDQ6VXNlcjE3NTgxMDI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1758102?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/luoyangylh",
          "html_url": "https://github.com/luoyangylh",
          "followers_url": "https://api.github.com/users/luoyangylh/followers",
          "following_url": "https://api.github.com/users/luoyangylh/following{/other_user}",
          "gists_url": "https://api.github.com/users/luoyangylh/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/luoyangylh/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/luoyangylh/subscriptions",
          "organizations_url": "https://api.github.com/users/luoyangylh/orgs",
          "repos_url": "https://api.github.com/users/luoyangylh/repos",
          "events_url": "https://api.github.com/users/luoyangylh/events{/privacy}",
          "received_events_url": "https://api.github.com/users/luoyangylh/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "aarohan",
          "id": 1788355,
          "node_id": "MDQ6VXNlcjE3ODgzNTU=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1788355?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aarohan",
          "html_url": "https://github.com/aarohan",
          "followers_url": "https://api.github.com/users/aarohan/followers",
          "following_url": "https://api.github.com/users/aarohan/following{/other_user}",
          "gists_url": "https://api.github.com/users/aarohan/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aarohan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aarohan/subscriptions",
          "organizations_url": "https://api.github.com/users/aarohan/orgs",
          "repos_url": "https://api.github.com/users/aarohan/repos",
          "events_url": "https://api.github.com/users/aarohan/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aarohan/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "robot9",
          "id": 1811913,
          "node_id": "MDQ6VXNlcjE4MTE5MTM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1811913?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/robot9",
          "html_url": "https://github.com/robot9",
          "followers_url": "https://api.github.com/users/robot9/followers",
          "following_url": "https://api.github.com/users/robot9/following{/other_user}",
          "gists_url": "https://api.github.com/users/robot9/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/robot9/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/robot9/subscriptions",
          "organizations_url": "https://api.github.com/users/robot9/orgs",
          "repos_url": "https://api.github.com/users/robot9/repos",
          "events_url": "https://api.github.com/users/robot9/events{/privacy}",
          "received_events_url": "https://api.github.com/users/robot9/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "sanyer",
          "id": 1888892,
          "node_id": "MDQ6VXNlcjE4ODg4OTI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1888892?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/sanyer",
          "html_url": "https://github.com/sanyer",
          "followers_url": "https://api.github.com/users/sanyer/followers",
          "following_url": "https://api.github.com/users/sanyer/following{/other_user}",
          "gists_url": "https://api.github.com/users/sanyer/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/sanyer/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/sanyer/subscriptions",
          "organizations_url": "https://api.github.com/users/sanyer/orgs",
          "repos_url": "https://api.github.com/users/sanyer/repos",
          "events_url": "https://api.github.com/users/sanyer/events{/privacy}",
          "received_events_url": "https://api.github.com/users/sanyer/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "Gwyendollen",
          "id": 1894442,
          "node_id": "MDQ6VXNlcjE4OTQ0NDI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1894442?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Gwyendollen",
          "html_url": "https://github.com/Gwyendollen",
          "followers_url": "https://api.github.com/users/Gwyendollen/followers",
          "following_url": "https://api.github.com/users/Gwyendollen/following{/other_user}",
          "gists_url": "https://api.github.com/users/Gwyendollen/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Gwyendollen/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Gwyendollen/subscriptions",
          "organizations_url": "https://api.github.com/users/Gwyendollen/orgs",
          "repos_url": "https://api.github.com/users/Gwyendollen/repos",
          "events_url": "https://api.github.com/users/Gwyendollen/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Gwyendollen/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "yoshi10321",
          "id": 1895209,
          "node_id": "MDQ6VXNlcjE4OTUyMDk=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1895209?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/yoshi10321",
          "html_url": "https://github.com/yoshi10321",
          "followers_url": "https://api.github.com/users/yoshi10321/followers",
          "following_url": "https://api.github.com/users/yoshi10321/following{/other_user}",
          "gists_url": "https://api.github.com/users/yoshi10321/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/yoshi10321/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/yoshi10321/subscriptions",
          "organizations_url": "https://api.github.com/users/yoshi10321/orgs",
          "repos_url": "https://api.github.com/users/yoshi10321/repos",
          "events_url": "https://api.github.com/users/yoshi10321/events{/privacy}",
          "received_events_url": "https://api.github.com/users/yoshi10321/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "shilezi",
          "id": 1895283,
          "node_id": "MDQ6VXNlcjE4OTUyODM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1895283?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/shilezi",
          "html_url": "https://github.com/shilezi",
          "followers_url": "https://api.github.com/users/shilezi/followers",
          "following_url": "https://api.github.com/users/shilezi/following{/other_user}",
          "gists_url": "https://api.github.com/users/shilezi/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/shilezi/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/shilezi/subscriptions",
          "organizations_url": "https://api.github.com/users/shilezi/orgs",
          "repos_url": "https://api.github.com/users/shilezi/repos",
          "events_url": "https://api.github.com/users/shilezi/events{/privacy}",
          "received_events_url": "https://api.github.com/users/shilezi/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "jessebikman",
          "id": 1895382,
          "node_id": "MDQ6VXNlcjE4OTUzODI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1895382?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/jessebikman",
          "html_url": "https://github.com/jessebikman",
          "followers_url": "https://api.github.com/users/jessebikman/followers",
          "following_url": "https://api.github.com/users/jessebikman/following{/other_user}",
          "gists_url": "https://api.github.com/users/jessebikman/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/jessebikman/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/jessebikman/subscriptions",
          "organizations_url": "https://api.github.com/users/jessebikman/orgs",
          "repos_url": "https://api.github.com/users/jessebikman/repos",
          "events_url": "https://api.github.com/users/jessebikman/events{/privacy}",
          "received_events_url": "https://api.github.com/users/jessebikman/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "turboho",
          "id": 1897173,
          "node_id": "MDQ6VXNlcjE4OTcxNzM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1897173?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/turboho",
          "html_url": "https://github.com/turboho",
          "followers_url": "https://api.github.com/users/turboho/followers",
          "following_url": "https://api.github.com/users/turboho/following{/other_user}",
          "gists_url": "https://api.github.com/users/turboho/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/turboho/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/turboho/subscriptions",
          "organizations_url": "https://api.github.com/users/turboho/orgs",
          "repos_url": "https://api.github.com/users/turboho/repos",
          "events_url": "https://api.github.com/users/turboho/events{/privacy}",
          "received_events_url": "https://api.github.com/users/turboho/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "yekowele",
          "id": 1898382,
          "node_id": "MDQ6VXNlcjE4OTgzODI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1898382?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/yekowele",
          "html_url": "https://github.com/yekowele",
          "followers_url": "https://api.github.com/users/yekowele/followers",
          "following_url": "https://api.github.com/users/yekowele/following{/other_user}",
          "gists_url": "https://api.github.com/users/yekowele/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/yekowele/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/yekowele/subscriptions",
          "organizations_url": "https://api.github.com/users/yekowele/orgs",
          "repos_url": "https://api.github.com/users/yekowele/repos",
          "events_url": "https://api.github.com/users/yekowele/events{/privacy}",
          "received_events_url": "https://api.github.com/users/yekowele/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "BoomBoxTV",
          "id": 1899537,
          "node_id": "MDQ6VXNlcjE4OTk1Mzc=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1899537?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/BoomBoxTV",
          "html_url": "https://github.com/BoomBoxTV",
          "followers_url": "https://api.github.com/users/BoomBoxTV/followers",
          "following_url": "https://api.github.com/users/BoomBoxTV/following{/other_user}",
          "gists_url": "https://api.github.com/users/BoomBoxTV/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/BoomBoxTV/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/BoomBoxTV/subscriptions",
          "organizations_url": "https://api.github.com/users/BoomBoxTV/orgs",
          "repos_url": "https://api.github.com/users/BoomBoxTV/repos",
          "events_url": "https://api.github.com/users/BoomBoxTV/events{/privacy}",
          "received_events_url": "https://api.github.com/users/BoomBoxTV/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "xrz",
          "id": 1899569,
          "node_id": "MDQ6VXNlcjE4OTk1Njk=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1899569?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/xrz",
          "html_url": "https://github.com/xrz",
          "followers_url": "https://api.github.com/users/xrz/followers",
          "following_url": "https://api.github.com/users/xrz/following{/other_user}",
          "gists_url": "https://api.github.com/users/xrz/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/xrz/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/xrz/subscriptions",
          "organizations_url": "https://api.github.com/users/xrz/orgs",
          "repos_url": "https://api.github.com/users/xrz/repos",
          "events_url": "https://api.github.com/users/xrz/events{/privacy}",
          "received_events_url": "https://api.github.com/users/xrz/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "Bhumik",
          "id": 1899762,
          "node_id": "MDQ6VXNlcjE4OTk3NjI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1899762?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Bhumik",
          "html_url": "https://github.com/Bhumik",
          "followers_url": "https://api.github.com/users/Bhumik/followers",
          "following_url": "https://api.github.com/users/Bhumik/following{/other_user}",
          "gists_url": "https://api.github.com/users/Bhumik/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Bhumik/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Bhumik/subscriptions",
          "organizations_url": "https://api.github.com/users/Bhumik/orgs",
          "repos_url": "https://api.github.com/users/Bhumik/repos",
          "events_url": "https://api.github.com/users/Bhumik/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Bhumik/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "velmurugansp",
          "id": 1901293,
          "node_id": "MDQ6VXNlcjE5MDEyOTM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1901293?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/velmurugansp",
          "html_url": "https://github.com/velmurugansp",
          "followers_url": "https://api.github.com/users/velmurugansp/followers",
          "following_url": "https://api.github.com/users/velmurugansp/following{/other_user}",
          "gists_url": "https://api.github.com/users/velmurugansp/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/velmurugansp/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/velmurugansp/subscriptions",
          "organizations_url": "https://api.github.com/users/velmurugansp/orgs",
          "repos_url": "https://api.github.com/users/velmurugansp/repos",
          "events_url": "https://api.github.com/users/velmurugansp/events{/privacy}",
          "received_events_url": "https://api.github.com/users/velmurugansp/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "AlinaAlimpescu",
          "id": 1901479,
          "node_id": "MDQ6VXNlcjE5MDE0Nzk=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1901479?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/AlinaAlimpescu",
          "html_url": "https://github.com/AlinaAlimpescu",
          "followers_url": "https://api.github.com/users/AlinaAlimpescu/followers",
          "following_url": "https://api.github.com/users/AlinaAlimpescu/following{/other_user}",
          "gists_url": "https://api.github.com/users/AlinaAlimpescu/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/AlinaAlimpescu/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/AlinaAlimpescu/subscriptions",
          "organizations_url": "https://api.github.com/users/AlinaAlimpescu/orgs",
          "repos_url": "https://api.github.com/users/AlinaAlimpescu/repos",
          "events_url": "https://api.github.com/users/AlinaAlimpescu/events{/privacy}",
          "received_events_url": "https://api.github.com/users/AlinaAlimpescu/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "johnnywell",
          "id": 1902036,
          "node_id": "MDQ6VXNlcjE5MDIwMzY=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1902036?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/johnnywell",
          "html_url": "https://github.com/johnnywell",
          "followers_url": "https://api.github.com/users/johnnywell/followers",
          "following_url": "https://api.github.com/users/johnnywell/following{/other_user}",
          "gists_url": "https://api.github.com/users/johnnywell/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/johnnywell/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/johnnywell/subscriptions",
          "organizations_url": "https://api.github.com/users/johnnywell/orgs",
          "repos_url": "https://api.github.com/users/johnnywell/repos",
          "events_url": "https://api.github.com/users/johnnywell/events{/privacy}",
          "received_events_url": "https://api.github.com/users/johnnywell/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "potentialcoder",
          "id": 1902154,
          "node_id": "MDQ6VXNlcjE5MDIxNTQ=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1902154?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/potentialcoder",
          "html_url": "https://github.com/potentialcoder",
          "followers_url": "https://api.github.com/users/potentialcoder/followers",
          "following_url": "https://api.github.com/users/potentialcoder/following{/other_user}",
          "gists_url": "https://api.github.com/users/potentialcoder/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/potentialcoder/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/potentialcoder/subscriptions",
          "organizations_url": "https://api.github.com/users/potentialcoder/orgs",
          "repos_url": "https://api.github.com/users/potentialcoder/repos",
          "events_url": "https://api.github.com/users/potentialcoder/events{/privacy}",
          "received_events_url": "https://api.github.com/users/potentialcoder/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "defunkt",
          "id": 2,
          "node_id": "MDQ6VXNlcjI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/2?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/defunkt",
          "html_url": "https://github.com/defunkt",
          "followers_url": "https://api.github.com/users/defunkt/followers",
          "following_url": "https://api.github.com/users/defunkt/following{/other_user}",
          "gists_url": "https://api.github.com/users/defunkt/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/defunkt/subscriptions",
          "organizations_url": "https://api.github.com/users/defunkt/orgs",
          "repos_url": "https://api.github.com/users/defunkt/repos",
          "events_url": "https://api.github.com/users/defunkt/events{/privacy}",
          "received_events_url": "https://api.github.com/users/defunkt/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "pjhyett",
          "id": 3,
          "node_id": "MDQ6VXNlcjM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/pjhyett",
          "html_url": "https://github.com/pjhyett",
          "followers_url": "https://api.github.com/users/pjhyett/followers",
          "following_url": "https://api.github.com/users/pjhyett/following{/other_user}",
          "gists_url": "https://api.github.com/users/pjhyett/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pjhyett/subscriptions",
          "organizations_url": "https://api.github.com/users/pjhyett/orgs",
          "repos_url": "https://api.github.com/users/pjhyett/repos",
          "events_url": "https://api.github.com/users/pjhyett/events{/privacy}",
          "received_events_url": "https://api.github.com/users/pjhyett/received_events",
          "type": "User",
          "site_admin": false
        }
      ]
      const renderItem = (item) => {
         
          return (
              <>
                <View style={styles.listStyle}>
                    <View style={styles.listContentStyle}>
                        <Image source={{uri:item.avatar_url}}
                            style={styles.listAvatarStyle}
                        />
                        <View>
                            <Text style={styles.listTextStyle}> UserName - {item.login}</Text>
                        </View>
                    </View>
                    <TouchableOpacity 
                        style={styles.listButtonStyle}
                        onPress={()=>{
                            navigation.navigate("User Profile")
                        }}
                    >
                        <Text style={styles.listButtonTextStyle}>View Profile</Text>
                    </TouchableOpacity>
                </View>
              </>
          )
      }
    return(
        <>
        <StatusBar backgroundColor="#334443" barStyle="light-content"/>
            <SafeAreaView style={{flex:1,backgroundColor:"#334443"}}>
                <View>
                    <Text style={styles.headerTextStyle}>Search for a user</Text>
                    <TextInput style={styles.textInputStyle}
                        placeholder="search user"
                        placeholderTextColor="#334443"
                    />
                </View>
                <View style={styles.containerStyle}>
                    <FlatList
                        data={Data}
                        renderItem={({item})=>{
                            return renderItem(item)
                        }}
                        showsVerticalScrollIndicator={false}
                        keyExtractor={({id})=>id}
                    />
                </View>
            </SafeAreaView>
        </>
    )
}

const styles = StyleSheet.create({
    headerTextStyle:{
        fontSize:hp("2.8%"),
        color:"#fffbdf",
        fontWeight:"700",
        alignSelf:"center",
        marginTop:hp("3%"),
        padding:hp("2%")
    },
    textInputStyle:{
        backgroundColor:"#c6ffc1",
        marginHorizontal:wp("5%"),
        borderRadius:10,
        padding:hp("2%"),
    },
    containerStyle:{
        flex:1,
        backgroundColor:"#fffbdf",
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        marginTop:hp("5%")
    },
    listStyle:{
        backgroundColor:"#34656d",
        borderRadius:20,
        marginVertical:hp("3%"),
        marginHorizontal:wp("5%"),
        elevation:10
    },
    listContentStyle:{
        flexDirection:"row"
    },
    listTextStyle:{
        top:hp("3%"),
        color:"#c6ffc1",
        fontSize:hp("2.5%")
    },
    listButtonTextStyle:{
        fontSize:hp("2.3%"),
        alignSelf:"center",
        color:"#939b62",
        fontWeight:"700",
        padding:hp("2%"),
        textAlign:"center"
    },
    listButtonStyle:{
        alignSelf:"flex-end",
        marginHorizontal:wp("2%"),
        marginVertical:hp("1.5%"),
        width:wp("30%"),
        backgroundColor:"#f0ebcc",
        borderRadius:7
    },
    listAvatarStyle:{
        marginHorizontal:wp("4%"),
        marginVertical:hp("2%"),
        height:70,
        width:70,
        borderRadius:35
    }
})

export default UsersScreen